# Starter pipeline
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise (011fd5e2-60c9-4a71-8bcd-659a9fbbfd4c)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'thinking'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'azure-deploy.json'
    csmParametersFile: 'azure-deploy.params.json'
    deploymentMode: 'Complete'

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'